#!/usr/bin/dh-exec
usr/bin/mysql_config
usr/include/mysql/*.h
usr/include/mysql/private/*.h
usr/include/mysql/psi/*.h
usr/lib/*/libmariadbclient.a
usr/lib/*/libmariadbclient.so
usr/lib/*/libmariadbclient_r.a
usr/lib/*/libmariadbclient_r.so*
usr/lib/*/libmysqlservices.a
usr/share/aclocal/mysql.m4
usr/share/man/man1/mysql_config.1
usr/share/pkgconfig/mariadb.pc usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig/
