debian/additions/innotop/innotop usr/bin/
debian/additions/mariadb.conf.d/50-client.cnf etc/mysql/mariadb.conf.d
debian/additions/mariadb.conf.d/50-mysql-clients.cnf etc/mysql/mariadb.conf.d
debian/additions/mysqlreport usr/bin/
usr/bin/mysql_find_rows
usr/bin/mysql_fix_extensions
usr/bin/mysql_waitpid
usr/bin/mysqlaccess
usr/bin/mysqladmin
usr/bin/mysqldump
usr/bin/mysqldumpslow
usr/bin/mysqlimport
usr/bin/mysqlshow
usr/bin/mysqlslap
